apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: roboshop-dev
  labels:
    app: nginx
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx:1.25
    ports:
    - containerPort: 80
    