apiVersion: v1
kind: Pod
metadata:
  name: -roboshop-dev-pod
  namespace: roboshop-dev
  labels:
    app: myapp
    tier: frontend
spec:
  containers:
  - name: myapp-container
    image: nginx:latest
    ports:
    - containerPort: 80
