apiVersion: v1
kind: Pod
metadata:
  name: front-end
  labels:
    project: roboshop
    app: front-end
    environment: development
    version: v1
spec:
  containers:
  - name: front-end
    image: nginx:1.25