apiVersion: v1
kind: pod
metadata:
  name: config-map-pod
spec:
  containers:
    - name: config-map-container
      image: nginx
      envFrom:
        - configMapRef:
            name: pod-config-map