apiVersion: v1
kind: pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: secret-container
    image: nginx
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: pod-secret
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pod-secret
          key: password