apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    project: roboshop
    components: frontend
    environment: dev
spec:
  selector:
    app: secret-pod   # must match the labels on your Pod/Deployment
  ports:
  - protocol: TCP
    port: 80        # service port
    targetPort: 80  # container port
  type: ClusterIP
