apiVersion: v1
kind: Service
metadata:
  name: ngnix
spec:
  selector:
  project: roboshop
  components: frontend
  env: dev
  ports:
  - protocol: TCP
    port: 80 #sevice port
    targetPort: 80 #container port