apiVersion: v1
kind: Pod
metadata:
  name: service-pod
spec:
  containers: 
   labels:
    project: roboshop
    components: frontend
    environment: dev

  spec:
   containers: 
    - name: nginx-container
      image: nginx