apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  types: NodePort
  selector:
    project: roboshop
    components: frontend 
    environment: dev
    porpose: node-port
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
